### PR TITLE
fix findOneAndRemove

### PR DESCRIPTION
**Pull request by jordonias**
Simple fix for fineOneAndRemove.

### CODE REVIEW

**Comment by jordonias** [comment]
I was able to get everythign working with the code below. Still can't produce the same error though. Make sure you are requiring in the same order.

``` tungus > mongoose > mongoose-auto-increment ```

```
var tungus = require('tungus');
var mongoose = require('mongoose');
var autoIncrement = require('mongoose-auto-increment');
var Schema = mongoose.Schema;

var connection = mongoose.connect('tingodb://' + __dirname + '/data');

autoIncrement.initialize(connection);

function strLenValidator() {
  return true;
}

var DeviceSchema = new Schema({
  id: Number,
  ukey: { type: String },
  title: { type: String, required: true, validate: strLenValidator },
  about: { type: String, required: true, validate: strLenValidator},
  tags: { type: [String], required: true },
  location: {
    local: { type: String, required: true, validate: strLenValidator},
    latitude: { type: Number, min: -90, max: 90 },
    longitude: { type: Number, min: -180, max: 180 }
  }
});

DeviceSchema.plugin(autoIncrement.plugin, {
  model: 'Device',
  field: 'id',
  startAt: 1,
  incrementBy: 1
});

var DeviceModel = mongoose.model('Device', DeviceSchema);

DeviceModel.findOneAndRemove({
  id: 7, //req.params.dvid,
  ukey: 1, //req.ukey
}, function (err, dv) {
  console.log(err);
  console.log(dv);
});
```

**Comment by glevine** [comment]
Just to bump this issue up... I ran into this problem by calling `findByIdAndRemove`.

**Comment by jordonias** [comment]
Do you still get `has no method 'apply'` like @jacle169 ?

**Comment by davidcl64** [comment]
+1

I ran into this as well with one of my collections - adding the fix above got me passed the problem.

**Comment by sergeyksv** [comment]
Actual cause was tingodb which was fix for this issues since 0.4.1. Thank you for your efforts but this fix is not required any more.

**Comment by jacle169** [comment]
Good job!!!

**Pull request closed without merging**
